// <auto-generated />

using System.CodeDom.Compiler;
using System.Resources;
using System.Data.Entity.Migrations.Infrastructure;

namespace Data.Persistence.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201908211636308_initialModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
